### PR TITLE
Jonasfj rewrite

### PR DESCRIPTION
**Pull request by jonasfj**
Made a few changes and rebased everything on top of `master` from `taskcluster-aws-provisioner2` heroku app...

Yeah... Not sure what you pushed to heroku, but not `rewrite` branch... or maybe it's just a long time since you pushed to heroku. Or maybe I did something very wrong...

If you don't like the hacks you can go back to the `v89  Deploy 2b78c57                            jhford@mozilla.com    2015/04/24 03:09:36` release on heroku.

My main chance here adding `_.omit(cfg.get('aws'), 'region')` for AWS provision... provide a description and default region for AWS... so we now have references and schemas uploaded to S3.

### CODE REVIEW

**Comment by jonasfj** [comment]
Reallly, not sure how I got this so backwards... hmm... LOL, maybe I rebased the wrong way :)

**Comment by jhford** [comment]
I'm not sure what's going in here, but the comits that you seem to have added look fine to me.

I'm going to cherry pick them onto a branch that I know is good.

**Comment by jhford** [comment]
```
commit eaea96a5ca593b23a0c7bbf9431d3cc79bcf20cd
Author: Jonas Finnemann Jensen <jopsen@gmail.com>
Date:   Mon Apr 27 13:45:50 2015 -0700

    Give an exchange description

commit 9e373146f0d0fa1beb5f83c7113235c7aefeee38
Author: Jonas Finnemann Jensen <jopsen@gmail.com>
Date:   Mon Apr 27 13:21:42 2015 -0700

    Set default region for AWS, but omit it for Aws thingiy config
```

**Comment by jonasfj** [comment]
@jhford, you might have to force push to heroku the next time...

**Pull request closed without merging**
