### PR TITLE
update secret docs

### PR DESCRIPTION
**Pull request by djmitche**
I'll be happy to rebase this after #32 lands.

### CODE REVIEW

**Comment by jhford** [comment]
Looks good to me, other than the double quotes.  The provisioner uses single quotes everywhere and instead escapes where needed.  I have eslint as the first step of the `npm test` steps, so if you get mocha unit tests running, you can assume that any linter output was warnings only

**Comment by djmitche** [comment]
I get 46 problems from `npm test` on master, and now 46 on my branch (just force pushed)

**Comment by jhford** [comment]
46 unit test failures or 46 linting issues?

**Comment by djmitche** [comment]
✖ 46 problems (25 errors, 21 warnings)

so all linting failures

**Comment by jonasfj** [comment]
Looks good to me... Only note is that instead of saying "token" it would be nice to use the property name used in user-data. And then use it in back-ticks so it's clear that it's a property. Notice docs. etc. can contain markdown.

**Comment by djmitche** [comment]
updated to name the `securityToken` property.

**Comment by jhford** [comment]
Dustin, if you rebase onto current master, I can happily merge when it's a good time to restart the provisioner

**Comment by djmitche** [comment]
rebased

**Pull request merged**
