### PR TITLE
Bug 1184272: specify all API scopes as [[str]]

### PR DESCRIPTION
**Pull request by djmitche**
I think this is the last one!

### CODE REVIEW

**Comment by jhford** [comment]
As long as the linter and unit tests run clean, this looks good to me!

**Comment by djmitche** [comment]
Do those not run in travis?

**Comment by jhford** [comment]
it looks like travis is not running on this commit, or at least I can't see it doing that

**Comment by jhford** [comment]
Linter and tests pass when I run the tests manually.  Merging.

**Pull request merged**
